### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by GIOVANNI-75** [damonwonghv/youtube-search-api#1]
Bonjour ! 
i have a SyntaxError: Unexpected token ' in JSON at position 1 .
for info, i use this module on ios for a personal project, i already try it on android and it has no problem on ios this problem persists do you have any idea where it might come from?
for more info :
ExceptionsManager.js:179 SyntaxError: Unexpected token ' in JSON at position 1
    at JSON.parse (<anonymous>)
    at index.js:20
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:274
    at _callTimer (JSTimers.js:130)
    at _callImmediatesPass (JSTimers.js:181)
    at MessageQueue.callImmediates [as _immediatesCallback] (JSTimers.js:441)
    at MessageQueue.__callImmediates (MessageQueue.js:387)
    at MessageQueue.js:135

**Comment by damonwonghv** [comment]
> Bonjour ! 
> 
> i have a SyntaxError: Unexpected token ' in JSON at position 1 .
> 
> for info, i use this module on ios for a personal project, i already try it on android and it has no problem on ios this problem persists do you have any idea where it might come from?
> 
> for more info :
> 
> ExceptionsManager.js:179 SyntaxError: Unexpected token ' in JSON at position 1
> 
>     at JSON.parse (<anonymous>)
> 
>     at index.js:20
> 
>     at tryCallOne (core.js:37)
> 
>     at core.js:123
> 
>     at JSTimers.js:274
> 
>     at _callTimer (JSTimers.js:130)
> 
>     at _callImmediatesPass (JSTimers.js:181)
> 
>     at MessageQueue.callImmediates [as _immediatesCallback] (JSTimers.js:441)
> 
>     at MessageQueue.__callImmediates (MessageQueue.js:387)
> 
>     at MessageQueue.js:135

Which framework you use?

**Comment by GIOVANNI-75** [comment]
I am using React-Native. the problem is just on IOS

**Comment by damonwonghv** [comment]
> I am using React-Native,the problem is just on IOS
Only tested on Node.js. Didn't work on native mobile. It suggested to host a Node.js server and write a API to call from the mobile. Hope it can help you.

**Comment by GIOVANNI-75** [comment]
yes I do that while waiting to find a native solution, thank you for taking the time to answer me.
