### ISSUE TITLE
please make index.d.ts

### ISSUE THREAD

**Issue by cottons-kr** [damonwonghv/youtube-search-api#10]
I want to use this but the project is using typescript. so i cant use it.

**Comment by damonwonghv** [comment]
Do you want to use it in the front end (react, vue) or node.js

**Comment by KillerDucks** [comment]
Hi just wanted to mention I am trying to use this in my own TypeScript project, so I am actually writing my own declaration file, I am happy to share it with @damonwonghv to merge in after I have created it and did some basic testing.

**Comment by eladcandroid** [comment]
@KillerDucks I would like to use it. Thanks!

**Comment by tronxdev** [comment]
@damonwonghv I've created index.d.ts for typescript support in recent days. Love to share it with all users.

**Comment by cottons-kr** [comment]
@tronxdev how can i use your declation file?

**Comment by KillerDucks** [comment]
I would PR my .d.ts but I have been ill past month so its not finished yet.
Here is the github doc for Pull Requests (PR) @tronxdev: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
