### ISSUE TITLE
youtube age restriction

### ISSUE THREAD

**Issue by mcitomiapplecat** [damonwonghv/youtube-search-api#11]
cannot find age-restricted videos. :/

**Comment by damonwonghv** [comment]
Any keywords you can provide as an example?

**Comment by mcitomiapplecat** [comment]
> Hi. It seems the problem is solved. Now you can find age-restricted content without any problems. Until now, instead of the original age-restricted music, the search engine prioritized bass boosted and other fan arrangements, and the original music was only found in 3rd or 4th place. I think it might be a youtube problem. The keyword I tried with: "krúbi üzenetek"
