### ISSUE TITLE
Is there is any daliy limit for search 

### ISSUE THREAD

**Issue by EswarSatti** [damonwonghv/youtube-search-api#18]
For youtube api as the daliy  limit of item as 8000 or 1000(roughly 80 to 100 search per day)  is thier any limit  of search

**Comment by damonwonghv** [comment]
> For youtube api as the daliy  limit of item as 8000 or 1000(roughly 80 to 100 search per day)  is thier any limit  of search

In theory, it may not have restrictions, since it just like your browser search.
