### ISSUE TITLE
Silence console logs

### ISSUE THREAD

**Issue by ThijmenGThN** [damonwonghv/youtube-search-api#19]
The module has been functioning superbly thus far, though I do have a comment regarding the messages it displays on the console when a fetch is initiated. Is it feasible to provide an option to disable the console logs?

![image](https://user-images.githubusercontent.com/54316157/220445194-b5874458-6a83-4ec3-8f06-68ba91a7cf42.png)

**Comment by damonwonghv** [comment]
Removed all console.log already. Only console.error for the current version.
