### ISSUE TITLE
CORS ?

### ISSUE THREAD

**Issue by jamenai** [damonwonghv/youtube-search-api#21]
![image](https://user-images.githubusercontent.com/1427936/224575891-11216681-c242-4c9e-afb7-4fa6fe8c2032.png)

I try to use the api from a local small webapp but ran in cors issues.

Whats wrong? ;-)

**Comment by thorn117** [comment]
The api does not work in the browser due to cors restrictions from YouTube (the browser checks the cross-origin headers, which are obviosly not valid for your app). You could wrap it in your own rest api (express, nestjs, ...)

**Comment by jamenai** [comment]
Nice, thank you for the quick answer!

**Comment by damonwonghv** [comment]
Tested and did some research already, it's hard to prevent CORS in a production environment, but you can use a clientside proxy to bypass it when development, after you built it may not work.
