### ISSUE TITLE
Getting captcha when deployed on a server. Possible workarounds?

### ISSUE THREAD

**Issue by Finalet** [damonwonghv/youtube-search-api#25]
First of, the library is great, and thank you for your work. 

When testing on my local machine, everything works, but, when deployed to a server, search requests are often blocked by captcha with the 429 error and body returns html page with captcha:

```
Error: Request failed with status code 429
statusText: 'Too Many Requests',
...
Our systems have detected unusual traffic from your computer network.  This page checks to see if it's really you sending the requests, and not a robot.
```

My sever could have bursts of 20-40 requests, which (I assume) is what triggering the captcha. This never happened when testing on my local machine.

I realized this is isn't a trivial request, but is there any best practices for avoiding captcha? Should I space out requests? Should I give up scraping if I need to make many requests at once? Is there any standard solutions for avoiding captcha?

**Comment by damonwonghv** [comment]
It's not possible to bypass the 429 Error. May I know how many requests per second and did you turn VPN?

**Comment by Finalet** [comment]
I have bursts of 25-50 requests and no VPN. Would it help?

**Comment by damonwonghv** [comment]
This is a brute force prevention technic implemented by Youtube, so it does not have any solution at this moment. Kindly remind, do not try to attack or brute force Youtube, they may block your IP address.
